{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "youtube-updater-tg-bot.secretName" . }}
  labels:
    {{- include "youtube-updater-tg-bot.labels" . | nindent 4 }}
type: Opaque
data:
  telegram-bot-token: {{ .Values.bot.telegramBotToken | b64enc }}
  youtube-api-key: {{ .Values.bot.youtubeApiKey | b64enc }}
  object-storage-access-key: {{ default "" .Values.objectStorage.accessKey | b64enc }}
  object-storage-secret-key: {{ default "" .Values.objectStorage.secretKey | b64enc }}
{{- end }}
