apiVersion: v1
kind: Service
metadata:
  name: {{ include "youtube-updater-tg-bot.fullname" . }}
  labels:
    {{- include "youtube-updater-tg-bot.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.service.port }}"
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "youtube-updater-tg-bot.selectorLabels" . | nindent 4 }}